Add skills deploy/undeploy cli commands
CognitiveScale/cortex-cli pull request #313
Opened 2021-04-16 14:41 UTC by jgielstra-cs

# Checklist:
Please check you fulfill ALL of the relevant checkboxes
- [ ] Notified docs of any potential USER-facing changes
- [ ] Added short description of the change - with relevant motivation and context. 
- [ ] Branch has the ticket number in its name (along with a ticket summary)
- [ ] Commented the code, particularly in hard-to-understand areas
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] Ran `npm test` and it passes
- [ ] Changes generate no new warnings

2021-04-16 16:12 UTC, daldridge-cs requested changes

2021-04-16 16:12 UTC, daldridge-cs commented on src/commands/skills.js
> +        debug('%s.executeUneDeploySkill(%s)', profile.name, skillName);
Typo nit: `unedeploy`?  Is that Italian? ;-)

2021-04-16 17:26 UTC, jlara-cs approved these changes

2021-04-16 17:43 UTC, clee-cs approved these changes
Couple small things David pointed out but good for the most part

2021-04-21 17:12 UTC, jgielstra-cs commented on src/commands/skills.js
> +        debug('%s.executeUneDeploySkill(%s)', profile.name, skillName);
copy pasta..

2021-04-21 17:15 UTC, merged