Release 2.0.3
CognitiveScale/cortex-cli pull request #325
Opened 2021-05-12 16:36 UTC by mcriscolo-cs

# Checklist:
Please check you fulfill ALL of the relevant checkboxes
- [ ] Notified docs of any potential USER-facing changes
- [ ] Added short description of the change - with relevant motivation and context. 
- [ ] Branch has the ticket number in its name (along with a ticket summary)
- [ ] Commented the code, particularly in hard-to-understand areas
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] Ran `npm test` and it passes
- [ ] Changes generate no new warnings

2021-05-12 17:08 UTC, smichalski-cs requested changes

2021-05-12 17:08 UTC, smichalski-cs commented on src/commands/assets/templates/skill/daemon/README.md
> +`make all` will build & push Docker image, deploy Cortex Action and Skill, and then invoke skill to test.
use "and" not "&".  Capitalize Skill after invoke.

2021-05-12 17:08 UTC, smichalski-cs commented on src/commands/assets/templates/skill/external-api/README.md
> +`make all` will deploy Cortex Skill, and then invoke skill to test.
Capitalize Skill after invoke

2021-05-12 17:08 UTC, smichalski-cs commented on src/commands/assets/templates/skill/job/README.md
> +`make all` will build & push Docker image, deploy Cortex Action and Skill, and then invoke skill to test.
use "and" not "&". Capitalize Skill after invoke.

2021-05-12 17:08 UTC, smichalski-cs commented on src/commands/assets/templates/skill/job/README.md
> +A Makefile is provided to do these steps. Set environment variables `DOCKER_PREGISTRY_URL` (like <docker-registry-url>/<namespace-org>) and `PROJECT_NAME` (Cortex Project Name) and use Makefile to de
Capitalize Skill

2021-05-12 17:08 UTC, smichalski-cs commented on src/commands/assets/templates/skill/daemon/README.md
> +A Makefile is provided to do these steps. Set environment variables `DOCKER_PREGISTRY_URL` (like <docker-registry-url>/<namespace-org>) and `PROJECT_NAME` (Cortex Project Name) and use Makefile to de
Capitalize Skill

2021-05-12 17:08 UTC, smichalski-cs commented on src/commands/plopfile.js
> +                message: 'Skill Name? (Must be alphanumeric)',
"Skill name must be alphanumeric, beginning with a letter. Hyphen and underscore allowed internally."

2021-05-12 17:08 UTC, smichalski-cs commented on src/commands/skills.js
> +                printError(`Failed to deploy skill ${skillName}: ${response.message}`, options);
Capitalize Skill

2021-05-12 17:08 UTC, smichalski-cs commented on src/commands/skills.js
> +                printError(`Failed to deploy skill ${skillName}: ${err.status} ${err.message}`, options);
Capitalize Skill

2021-05-12 17:08 UTC, smichalski-cs commented on src/commands/skills.js
> +                printSuccess(`Deployed skill ${skillName}: ${response.message}`, options);
Capitalize Skill

2021-05-12 17:08 UTC, smichalski-cs commented on src/commands/skills.js
> +                printError(`Failed to deploy skill ${skillName}: ${response.message}`, options);
Capitalize Skill

2021-05-12 17:08 UTC, smichalski-cs commented on src/commands/skills.js
> +                printError(`Failed to Undeploy skill ${skillName}: ${response.message}`, options);
capitalize Skill

2021-05-12 17:08 UTC, smichalski-cs commented on src/commands/skills.js
> +                printError(`Failed to Undeploy skill ${skillName}: ${response.message}`, options);
capitalize Skill

2021-05-12 17:08 UTC, smichalski-cs commented on src/commands/skills.js
> +                printError(`Failed to Undeploy skill ${skillName}: ${err.status} ${err.message}`, options);
capitalize Skill

2021-05-12 18:25 UTC, vkarumuri-cs approved these changes

2021-05-12 18:42 UTC, mcriscolo-cs commented on src/commands/skills.js
> +                printError(`Failed to Undeploy skill ${skillName}: ${err.status} ${err.message}`, options);
fixed

2021-05-12 18:42 UTC, mcriscolo-cs commented on src/commands/skills.js
> +                printError(`Failed to Undeploy skill ${skillName}: ${response.message}`, options);
fixed

2021-05-12 18:43 UTC, mcriscolo-cs commented on src/commands/skills.js
> +                printError(`Failed to Undeploy skill ${skillName}: ${response.message}`, options);
fixed

2021-05-12 18:43 UTC, mcriscolo-cs commented on src/commands/skills.js
> +                printError(`Failed to deploy skill ${skillName}: ${response.message}`, options);
fixed

2021-05-12 18:43 UTC, mcriscolo-cs commented on src/commands/skills.js
> +                printSuccess(`Deployed skill ${skillName}: ${response.message}`, options);
fixed

2021-05-12 18:43 UTC, mcriscolo-cs commented on src/commands/assets/templates/skill/daemon/README.md
> +`make all` will build & push Docker image, deploy Cortex Action and Skill, and then invoke skill to test.
fixed

2021-05-12 18:43 UTC, mcriscolo-cs commented on bin/cortex-secrets.js
> +    .description('Save or overwrite a secure value. By default, values are stored as strings but can also be saved as JSON or YAML values.')
fixed

2021-05-12 18:43 UTC, mcriscolo-cs commented on bin/cortex-docker.js
> +    .option('--ttl [time]', 'The amount of time for this login to remain active (ex. "14d")', '14d')
fixed

2021-05-12 18:43 UTC, mcriscolo-cs commented on bin/cortex-configure.js
> +    .option('--ttl [time]', 'The amount of time for this login to remain active (ex. "1d")', '1d')
fixed

2021-05-13 14:42 UTC, mcriscolo-cs commented on src/commands/assets/templates/skill/external-api/README.md
> +`make all` will deploy Cortex Skill, and then invoke skill to test.
fixed

2021-05-13 14:42 UTC, mcriscolo-cs commented on src/commands/assets/templates/skill/job/README.md
> +`make all` will build & push Docker image, deploy Cortex Action and Skill, and then invoke skill to test.
fixed

2021-05-13 14:43 UTC, mcriscolo-cs commented on src/commands/assets/templates/skill/daemon/README.md
> +A Makefile is provided to do these steps. Set environment variables `DOCKER_PREGISTRY_URL` (like <docker-registry-url>/<namespace-org>) and `PROJECT_NAME` (Cortex Project Name) and use Makefile to de
fixed

2021-05-13 14:43 UTC, mcriscolo-cs commented on src/commands/skills.js
> +                printError(`Failed to deploy skill ${skillName}: ${response.message}`, options);
fixed

2021-05-13 14:43 UTC, mcriscolo-cs commented on src/commands/skills.js
> +                printError(`Failed to deploy skill ${skillName}: ${err.status} ${err.message}`, options);
fixed

2021-05-13 14:43 UTC, mcriscolo-cs commented on src/commands/assets/templates/skill/job/README.md
> +A Makefile is provided to do these steps. Set environment variables `DOCKER_PREGISTRY_URL` (like <docker-registry-url>/<namespace-org>) and `PROJECT_NAME` (Cortex Project Name) and use Makefile to de
fixed

2021-05-13 14:43 UTC, mcriscolo-cs commented on src/commands/plopfile.js
> +                message: 'Skill Name? (Must be alphanumeric)',
fixed

2021-05-13 14:59 UTC, smichalski-cs approved these changes

2021-05-13 16:01 UTC, rsrivastava-cs approved these changes

2021-05-13 16:01 UTC, merged