FAB-2518 fix vulns, fix linting
CognitiveScale/cortex-cli pull request #401
Opened 2021-09-09 13:24 UTC by jgielstra-cs

Use newer js-yaml that is YAML 1.2 complaint, add -k for k8s resources

Add better error is config file is invalid

# Checklist:
Please check you fulfill ALL of the relevant checkboxes
- [X] Notified docs of any potential USER-facing changes
- [X] Added short description of the change - with relevant motivation and context. 
- [X] Branch has the ticket number in its name (along with a ticket summary)
- [X] Commented the code, particularly in hard-to-understand areas
- [ ] Added tests that prove my fix is effective or that my feature works
- [X] Ran `npm test` and it passes
- [X] Changes generate no new warnings

2021-09-09 14:24 UTC, daldridge-cs requested changes

2021-09-09 14:24 UTC, daldridge-cs commented on bin/cortex-actions.js
> +    .option('-k --k8sResource [file...]', 'Additional kubernetes resources deployed and owned by the skill')
For consistency, this should be `.option('-k, --k8sResource [file...]', ...` (add comma between shortcut and full option name).  See precendent in cortex-projects Create Project command, for example.

2021-09-09 15:58 UTC, mcriscolo-cs approved these changes

2021-09-10 14:11 UTC, jgielstra-cs commented on bin/cortex-actions.js
> +    .option('-k --k8sResource [file...]', 'Additional kubernetes resources deployed and owned by the skill')
Y let me try this .. guess commanders parser is very tolerant ...

2021-09-10 14:15 UTC, merged