FAB-1213 Options requiring a value should fail is value not provided,…
CognitiveScale/cortex-cli pull request #561
Opened 2022-05-05 14:39 UTC by jgielstra-cs

… remove configure related stack traces

Tweak boolean options

.

# Checklist:
Please check you fulfill ALL of the relevant checkboxes
- [x] Notified docs of any potential USER-facing changes
- [x] Added short description of the change - with relevant motivation and context. 
- [x] Branch has the ticket number in its name (along with a ticket summary)
- [x] Commented the code, particularly in hard-to-understand areas
- [x] Added tests that prove my fix is effective or that my feature works
- [x] Ran `npm test` and it passes
- [x] Changes generate no new warnings

2022-05-05 15:51 UTC, daldridge-cs requested changes

2022-05-05 15:51 UTC, daldridge-cs commented on bin/cortex-assessments.js
>      .option('--overwrite [boolean]', 'Overwrite existing assessment, if exists')
Inconsistency between `[on/off]`(w.g. --color), and `[boolean]`?

2022-05-06 16:17 UTC, clee-cs approved these changes

2022-05-06 17:05 UTC, jgielstra-cs commented on bin/cortex-actions.js
> +    .option('--color <on/off>', 'Turn on/off colors for JSON output.', 'on')
Yeah was waffling on using a parseBoolean() library for backward compatibility..

we check `options.color==on`

2022-05-17 10:39 UTC, akprasad-cs approved these changes

2022-05-19 16:20 UTC, merged